trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || echo "No build step"
  displayName: 'Install and Build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'okToya'
    appType: 'webAppLinux'
    appName: 'sample-app-faisal-demo'
    package: '$(System.DefaultWorkingDirectory)'
