trigger:
  branches:
    include:
      - main  # Change if you use a different branch

pool:
  name: default
  demands:
    - agent.name -equals my-wsl-agent  # Change if your agent is named differently

variables:
  appName: 'sample-app-faisal-demo'  # 🔁 Replace with your Azure App Service name
  azureSubscription: 'okToya'  # 🔁 Replace with your Service Connection name

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || echo "No build step, skipping"
  displayName: 'Install dependencies and build app'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Zip application'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy to Azure App Service'

